f = open("./entrada.txt", "r", encoding="utf-8")
print("\\t")
entrada0 = f.read()
entrada1 = entrada0.replace('\\n',"\n")
entrada2 = entrada1.replace('\\\\',"\\")
entrada3 = entrada2.replace('\\"','"')
entrada4 = entrada3.replace("\\t"," ")
entrada5 = entrada4.replace("\\'","'")
print(entrada5)